language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: dFdtizbH81EHuCjRr3YQeR8ko38dYdltJyQ/altRhjb0PzJVCFaJ1PO1rFe/TUBL3u5FyRH9GrmyXNs7bkKm4xgPfLuWASfpcyBa+ZJnQdDgY2HSMW6T4X9Hobged9V1QjnxNn/EhDeMZcVJaqOOrGkVl9YhKwX+/QSKWFRxEB8=
  - secure: DWv3v7t52eCxATOtLp6antPIlIPVnloEwqWyZJQGAmKiyFiiV5WL1bWdLUS9dD2yUdnJ7Ylq8ESqYskKjMYdwmL3HFJ7s4dMGaOHJ8IFRivY+5oN2KCum4T0Ysbs1029HcvJYdew30HMT4USjLKqQW1ZCWXriW2f64XtqE9YvzQ=
